name: TDR Deploy File Metadata
on:
  workflow_dispatch:
env:
  RUN_NUMBER: ${{ github.run_id }}${{ github.run_attempt }}
  BRANCH_NAME: version-bump-${{ github.run_id }}${{ github.run_attempt }}
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v4
        with:
          git_user_signingkey: true
          git_commit_gpgsign: true
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
      - run: |
          ./.github/scripts/deploy_npm.sh ${{ secrets.NPM_TOKEN }}
        id: deploy-npm
      - name: Create Pull Request
        run: gh pr create --fill --label 'Version bump'
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_PAT }}
      - name: Send success message
        uses: nationalarchives/tdr-github-actions/.github/actions/slack-send@main
        with:
          message: ":white_check_mark: File metadata ${{ steps.deploy-npm.outputs.set-npm-version }} has been published"
          slack-url: ${{ secrets.SLACK_WEBHOOK }}
